### ISSUE TITLE
ioCreateDriver fails with 0xC0000033 (STATUS_OBJECT_NAME_INVALID)

### ISSUE THREAD

**Issue by jocmer** [hfiref0x/TDL#13]
I've got this problem only if try to load the driver on my main system. In VMs it works perfectly fine.

`status = IoCreateDriver(&drvName, &DriverInitialize);
DbgPrint("%s IoCreateDriver(%wZ) = %lx", __FUNCTION__, drvName, status);
`

**Comment by hfiref0x** [comment]
Show your drvName.

**Comment by jocmer** [comment]
WCHAR szDrvName[] = { L'\\', L'D', L'r', L'i', L'v', L'e', L'r', L'\\', L'T', L'P', L'L', L'D', 0 };

**Comment by hfiref0x** [comment]
Well yes it is incorrect. Instead of backslash characters you coded escape sequences \D and \T.

WCHAR szDrvName[] = { L'\\', L'D', L'r', L'i', L'v', L'e', L'r', L'\\', L'T', L'P', L'L', L'D', 0 };

**Comment by hfiref0x** [comment]
Initially I thought the problem was in escape sequence, but it turns out this is how github editor converted text. Does it enter to DriverInitialize and where it returns from it? Show some debug output from DriverInitialize. Note that it calls IoCreateDevice and IoCreateSymbolicLink here, so please post their status codes. And if you changed \Driver\TDLD to \Driver\TPLD then change \Device\TDLD to \Device\TPLD and \DosDevices\TDLD to \DosDevices\TPLD.
