### ISSUE TITLE
BSOD [Kernel Security Check Failure] on 14393.1593 and 15063.540 

### ISSUE THREAD

**Issue by Trojaner** [hfiref0x/TDL#20]
Tried to run the precompiled TDL with the dummy2 driver
Reproduced this on my own computer with build 15063.540 and on a vmware virtual machine with build 14393.1593.

DMP from 15063 [082617-48640-01.zip](https://github.com/hfiref0x/TDL/files/1253821/082617-48640-01.zip)

**Comment by hfiref0x** [comment]
Your dump is useless and broken.

**Comment by Trojaner** [comment]
Thanks, tell me how to get a better dump and I will provide you it.

I got it from C:\Windows\Minidump

**Comment by hfiref0x** [comment]
Well it should be at least - full memory dump. But what exactly do you want me to look here? This is not productional software, it BSOD because it is not intended to work from the beginning. It is system hack entirely based on third party driver from Oracle which is bug fest by design. So unlikely any fix will be provided. Consider this as sort of abandonware.

**Comment by Trojaner** [comment]
Sad to hear, but understandable.
The full Memory Dump is something I can not upload, it is about 1,6 GB big and my connection will not allow me to do that.
