### ISSUE TITLE
Failed windows 10 pro x64

### ISSUE THREAD

**Issue by DonoDayZ** [hfiref0x/TDL#32]
Turla Driver Loader v1.1.4 started
(c) 2016 - 2019 TDL Project
Supported x64 OS : 7 and above

Ldr: Windows v10.0 build 17763
SCM: Vulnerable driver load failure

I did everything right and I get this, I have already checked all the driver and have no running to lock it.

**Comment by hfiref0x** [comment]
![Untitled](https://user-images.githubusercontent.com/10708977/56074462-67138980-5ddd-11e9-9f64-f02e904b0ff8.png)

Likely it is your environment caused.

P.S.
Also this maybe related to VBoxDrv.sys failed to load because of Windows 10 driver signing policy change. Check this out https://techcommunity.microsoft.com/t5/Windows-Hardware-Certification/Driver-Signing-changes-in-Windows-10-version-1607/ba-p/364894

**Comment by hfiref0x** [comment]
18 days no reply, closed.

**Comment by MeisterJaan** [comment]
I am having the same issue
![image](https://user-images.githubusercontent.com/48528364/57581797-4ebe8980-74c5-11e9-8896-706b218ed1f2.png)
"
@hfiref0x

**Comment by quetzalsly** [comment]
So with the new windows 10 we can't use this anymore? I am still on windows 7 but dreading the future :(

**Comment by hfiref0x** [comment]
If you expected this to work forever it is obviosly your problem.
